Update db-xrefs.yaml
geneontology/go-site pull request #1604
Opened 2020-12-21 20:36 UTC by zhilianghu

Added xref for (1) animal QTLdb; (2) animal CorrDB

2020-12-21 21:26 UTC, kltm requested changes

2020-12-21 21:26 UTC, kltm commented on metadata/db-xrefs.yaml
> +    - url_syntax: https://www.animalgenome.org/QTLdb/q?id=[QTL_ID]
This should probably be `[example_id]`

2020-12-21 21:26 UTC, kltm commented on metadata/db-xrefs.yaml
> +    - example_id: 23155
This would need to be a CURIE

2020-12-21 21:26 UTC, kltm commented on metadata/db-xrefs.yaml
> +    - example_id: 37232
This would need to be a CURIE

2020-12-21 21:26 UTC, kltm commented on metadata/db-xrefs.yaml
> +- database: Animal QTLdb
This needs to be the CURIE namespace.

2020-12-21 21:26 UTC, kltm commented on metadata/db-xrefs.yaml
> +- database: Animal CorrDB
This needs to be the CURIE namespace.

2020-12-21 23:37 UTC, zhilianghu commented on metadata/db-xrefs.yaml
> +    - example_id: 37232
Yes; Changed to [Animal_QTLdb]

2020-12-21 23:38 UTC, zhilianghu commented on metadata/db-xrefs.yaml
> +    - url_syntax: https://www.animalgenome.org/QTLdb/q?id=[QTL_ID]
Changed

2020-12-21 23:38 UTC, zhilianghu commented on metadata/db-xrefs.yaml
> +- database: Animal CorrDB
Changed to [Animal_CorrDB]

2020-12-21 23:40 UTC, zhilianghu commented
Did another push.

2020-12-21 23:46 UTC, kltm commented
Your PR is still failing:
```
0.16s$ kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
metadata/db-xrefs.yaml#0: INVALID
metadata/db-xrefs.yaml:2892:3 [/264/generic_urls] 'https://www.animalgenome.org/QTLdb': not a sequence.
metadata/db-xrefs.yaml:2895:7 [/264/entity_types/0] key 'type_id:' is required.
metadata/db-xrefs.yaml:2896:7 [/264/entity_types/1] key 'type_name:' is required.
metadata/db-xrefs.yaml:2896:7 [/264/entity_types/1] key 'type_id:' is required.
metadata/db-xrefs.yaml:2897:7 [/264/entity_types/2] key 'type_id:' is required.
metadata/db-xrefs.yaml:2897:7 [/264/entity_types/2] key 'type_name:' is required.
metadata/db-xrefs.yaml:2898:7 [/264/entity_types/3] key 'type_name:' is required.
metadata/db-xrefs.yaml:2898:7 [/264/entity_types/3] key 'type_id:' is required.
metadata/db-xrefs.yaml:2898:7 [/264/entity_types/3/example_id] '23155': not a string.
metadata/db-xrefs.yaml:2899:7 [/264/entity_types/4] key 'type_id:' is required.
metadata/db-xrefs.yaml:2899:7 [/264/entity_types/4] key 'type_name:' is required.
metadata/db-xrefs.yaml:2900:3 [/265] key 'generic_urls:' is required.
metadata/db-xrefs.yaml:2904:7 [/265/entity_types/0] key 'type_id:' is required.
metadata/db-xrefs.yaml:2905:7 [/265/entity_types/1] key 'type_name:' is required.
metadata/db-xrefs.yaml:2905:7 [/265/entity_types/1] key 'type_id:' is required.
metadata/db-xrefs.yaml:2906:7 [/265/entity_types/2] key 'type_name:' is required.
metadata/db-xrefs.yaml:2906:7 [/265/entity_types/2] key 'type_id:' is required.
metadata/db-xrefs.yaml:2907:7 [/265/entity_types/3] key 'type_name:' is required.
metadata/db-xrefs.yaml:2907:7 [/265/entity_types/3] key 'type_id:' is required.
metadata/db-xrefs.yaml:2907:7 [/265/entity_types/3/example_id] '37232': not a string.
metadata/db-xrefs.yaml:2908:7 [/265/entity_types/4] key 'type_id:' is required.
metadata/db-xrefs.yaml:2908:7 [/265/entity_types/4] key 'type_name:' is required.
metadata/db-xrefs.yaml#0: INVALID
The command "kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0" exited with 1.
```
You might want to take a look at YAML and the schema: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.schema.yaml

2020-12-23 20:53 UTC, zhilianghu commented
Updated with generic URL, type_id, type_name, and example_ID.

2021-01-07 05:25 UTC, kltm commented
@zhilianghu I believe that these should not have brackets:
` - database: [Animal_CorrDB]`
As well, the tests are not passing at these points:
https://travis-ci.org/github/geneontology/go-site/builds/751254307#L1095
https://travis-ci.org/github/geneontology/go-site/builds/751254307#L1107
generic_urls are a YAML list. You can either look at the schema (https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.schema.yaml) or other examples in the file.

2021-01-07 15:48 UTC, zhilianghu commented
Thank you for your patience with me.  New changes are made.

2021-01-13 02:14 UTC, kltm commented
@zhilianghu You may want to look at the schema or one of the other entries in the file that is close to yours in content and mimic it--it appears that your are confusing list and "dictionary" structures in YAML, with the overuse of `-`.
https://travis-ci.org/github/geneontology/go-site/builds/753374096#L1093

As you work on your PR, you can see the current status under "Details" after "All checks have failed". The part that you'd be interested in would be after:
```
kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
```
You can see the errors after that.

2021-01-13 04:42 UTC, kltm commented
This looks clean to me.

@dougli1sqrd Would you mind taking a quick look at this too to make sure nothing looks off?

2021-01-13 21:02 UTC, dougli1sqrd commented
This seems good!

2021-01-13 21:07 UTC, merged