change https-> http to match minerva URI expansion for SGD
geneontology/go-site pull request #2176
Opened 2023-11-15 22:28 UTC by sierra-moxon

2023-11-16 00:03 UTC, kltm commented
This can be merged with the agreement of @balhoff or @cmungall

2023-11-16 00:05 UTC, kltm approved these changes
I believe this is true for this specific case, but what about:
```
sjcarbon@moiraine:~/local/src/git/go-site/metadata[master]$:) grep 'https://identifiers.org' db-xrefs.yaml 
  rdf_uri_prefix: https://identifiers.org/maizegdb.locus
  rdf_uri_prefix: https://identifiers.org/metacyc.reaction
  rdf_uri_prefix: https://identifiers.org/MGI
  rdf_uri_prefix: https://identifiers.org/ncbigene
  rdf_uri_prefix: https://identifiers.org/panther.family
  rdf_uri_prefix: https://identifiers.org/plasmodb
  rdf_uri_prefix: https://identifiers.org/pombase
  rdf_uri_prefix: https://identifiers.org/reactome
  rdf_uri_prefix: https://identifiers.org/rgd
  rdf_uri_prefix: https://identifiers.org/sgd
  rdf_uri_prefix: https://identifiers.org/sgn
  rdf_uri_prefix: https://identifiers.org/tair.locus
  rdf_uri_prefix: https://identifiers.org/tgd
  rdf_uri_prefix: https://identifiers.org/tritrypdb
  rdf_uri_prefix: https://identifiers.org/uniprot
  rdf_uri_prefix: https://identifiers.org/wb
  rdf_uri_prefix: https://identifiers.org/xenbase
  rdf_uri_prefix: https://identifiers.org/zfin
```

2023-11-16 03:35 UTC, balhoff requested changes

2023-11-16 03:35 UTC, balhoff commented on metadata/db-xrefs.yaml
> +  rdf_uri_prefix: http://identifiers.org/sgd
@sierra-moxon this change looks good but it seems like this namespace should also have a trailing slash in order for the URI construction to be correct.

2023-11-16 03:35 UTC, balhoff commented on metadata/db-xrefs.yaml
> +  rdf_uri_prefix: http://identifiers.org/sgd
```suggestion
  rdf_uri_prefix: http://identifiers.org/sgd/
```

2023-11-16 21:25 UTC, kltm commented
```
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:( cat *.ttl | grep -c "http://registry.identifiers.org"
0
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:( cat *.ttl | grep -c "http://identifiers.org"
211694
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:) cat *.ttl | grep -c "https://identifiers.org"
0
```

2023-11-16 21:26 UTC, kltm commented
TODO: add trailing slashes and the above identifiers.

2023-11-28 23:30 UTC, sierra-moxon commented
I tested these changes via the API and I think they are good to go w/re to expanding SGD curies.  I noticed an expansion problem with wormbase beyond the https issue, and changed it to be equivalent to https://github.com/geneontology/minerva/blob/master/minerva-core/src/main/resources/go_context.jsonld instead. 
Same with interpro

2023-11-29 16:30 UTC, balhoff approved these changes

2024-07-17 22:01 UTC, kltm commented
Noting @balhoff approval above; following up on https://github.com/geneontology/go-site/pull/2176#issuecomment-1813490576

2024-07-17 22:01 UTC, merged

2024-07-17 22:01 UTC, kltm commented
https://github.com/geneontology/go-fastapi/issues/98